# Generated by Django 2.2.4 on 2020-05-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Narmadiya', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Patrika/Images', verbose_name='Image')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Name of Patrika')),
                ('description', models.CharField(default='', max_length=500, verbose_name='Description of Patrika')),
                ('pdf', models.FileField(upload_to='Patrika/pdf', verbose_name='File')),
            ],
        ),
    ]
