# Generated by Django 2.2.4 on 2020-05-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Narmadiya', '0002_patrika'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.ImageField(default='', upload_to='News/Images', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='news',
            name='photo2',
            field=models.ImageField(default='', upload_to='News/Images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='images',
            field=models.ImageField(default='', upload_to='News/Images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='patrika',
            name='pdf',
            field=models.FileField(default='', upload_to='Patrika/pdf', verbose_name='File'),
        ),
    ]
