# Generated by Django 2.2.4 on 2020-05-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Narmadiya', '0003_auto_20200523_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='News/Images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo2',
            field=models.ImageField(blank=True, default='', upload_to='News/Images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='video',
            field=models.FileField(blank=True, upload_to='News/Video', verbose_name='Video'),
        ),
    ]
