# Generated by Django 2.2.4 on 2020-05-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Narmadiya', '0005_auto_20200523_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='video',
            field=models.FileField(blank=True, default='settings.MEDIA_ROOT/News/Video/default.mp4', upload_to='News/Video', verbose_name='Video'),
        ),
    ]
