# Generated by Django 2.2.4 on 2020-05-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Narmadiya', '0006_auto_20200523_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news',
            field=models.CharField(default='', max_length=5000, verbose_name='News'),
        ),
        migrations.AlterField(
            model_name='news',
            name='video',
            field=models.FileField(default='settings.MEDIA_ROOT/News/Video/default.mp4', upload_to='News/Video', verbose_name='Video'),
        ),
    ]
