# Generated by Django 2.2.4 on 2020-05-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Narmadiya', '0007_auto_20200523_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='video',
            field=models.FileField(default='media/News/Video/default.mp4', upload_to='News/Video', verbose_name='Video'),
        ),
    ]
