# Generated by Django 2.2.4 on 2020-05-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Narmadiya', '0009_auto_20200523_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, default='News/Images/galactic_interstellar_5k.jpg', upload_to='News/Images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='video',
            field=models.FileField(blank=True, default='News/Video/default.mp4', upload_to='News/Video', verbose_name='Video'),
        ),
    ]
