# Generated by Django 2.2.4 on 2020-05-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Narmadiya', '0012_auto_20200523_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='heading',
            field=models.CharField(default='', max_length=100, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(default='', upload_to='News/Images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='video',
            field=models.FileField(default='', upload_to='News/Video', verbose_name='Video'),
        ),
    ]
