# Generated by Django 2.2.4 on 2020-05-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Narmadiya', '0013_auto_20200523_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=20, verbose_name='First Name')),
                ('lname', models.CharField(default='', max_length=20, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.BigIntegerField(verbose_name='Phone Number')),
                ('description', models.CharField(default='', max_length=500, verbose_name='Description of the Advertisement')),
                ('content', models.FileField(default='', upload_to='Adv/Images', verbose_name='File')),
            ],
        ),
    ]
