# Generated by Django 2.2.4 on 2020-05-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Narmadiya', '0016_auto_20200524_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='content',
            field=models.FileField(default='', upload_to='Adv/Images', verbose_name='File'),
        ),
    ]
