# Generated by Django 2.2.4 on 2020-05-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Narmadiya', '0017_auto_20200525_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dharmik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Title')),
                ('description', models.CharField(max_length=500000, verbose_name='Description')),
            ],
        ),
    ]
