# Generated by Django 2.2.4 on 2020-05-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Narmadiya', '0018_dharmik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matrimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('madeby', models.CharField(default='', max_length=50, verbose_name='Made By')),
                ('Name', models.CharField(default='', max_length=50, verbose_name='Full Name')),
                ('fName', models.CharField(default='', max_length=50, verbose_name="Father's  Name")),
                ('mName', models.CharField(default='', max_length=50, verbose_name="Mother's  Name")),
                ('gender', models.CharField(default='', max_length=30, verbose_name='Gender')),
                ('photo', models.FileField(default='', max_length=30, upload_to='', verbose_name='Photo')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('marital', models.CharField(default='', max_length=30, verbose_name='Marital Status')),
                ('height', models.CharField(default='', max_length=30, verbose_name='Height')),
                ('mothertongue', models.CharField(default='', max_length=50, verbose_name='Mother Tongue')),
                ('nationality', models.CharField(default='', max_length=30, verbose_name='Nationality')),
                ('mobileno', models.BigIntegerField(default='', verbose_name='Mobile Number')),
                ('altmobileno', models.BigIntegerField(default='', verbose_name=' Alternate Mobile Number')),
                ('fmobileno', models.BigIntegerField(default='', verbose_name="Father's Mobile Number")),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Email')),
                ('education', models.CharField(default='', max_length=50, verbose_name='Education')),
                ('job', models.CharField(default='', max_length=50, verbose_name='Job Type')),
                ('nakshatra', models.CharField(default='', max_length=50, verbose_name='Nakshatra')),
                ('rashi', models.CharField(default='', max_length=50, verbose_name='Rashi')),
                ('gautra', models.CharField(default='', max_length=50, verbose_name='Gautra')),
                ('dosh', models.CharField(default='', max_length=50, verbose_name='Dosh')),
                ('patrikamilan', models.CharField(default='', max_length=20, verbose_name='Patrika Milan')),
                ('road', models.CharField(default='', max_length=150, verbose_name='Road')),
                ('post', models.CharField(default='', max_length=30, verbose_name='Post')),
                ('tehsil', models.CharField(default='', max_length=50, verbose_name='Tehsil')),
                ('jila', models.CharField(default='', max_length=50, verbose_name='Jila')),
                ('pincode', models.CharField(default='', max_length=30, verbose_name='Pin Code')),
                ('rajya', models.CharField(default='', max_length=30, verbose_name='Rajya')),
            ],
        ),
    ]
