# Generated by Django 2.2.4 on 2020-05-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Narmadiya', '0019_matrimony'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrimony',
            name='education',
        ),
        migrations.RemoveField(
            model_name='matrimony',
            name='nationality',
        ),
        migrations.AddField(
            model_name='matrimony',
            name='mama',
            field=models.CharField(default='', max_length=30, verbose_name='Name of Maternal Uncle'),
        ),
        migrations.AddField(
            model_name='matrimony',
            name='mamagautra',
            field=models.CharField(default='', max_length=30, verbose_name='Maternal Uncle Gautra'),
        ),
        migrations.AddField(
            model_name='matrimony',
            name='noOfBroSis',
            field=models.IntegerField(default=0, verbose_name='Number of Brothers and Sisters'),
        ),
        migrations.AddField(
            model_name='matrimony',
            name='placeofbirth',
            field=models.CharField(default='', max_length=30, verbose_name='Place of Birth'),
        ),
        migrations.AddField(
            model_name='matrimony',
            name='qualification',
            field=models.CharField(default='', max_length=50, verbose_name='Qualifications'),
        ),
    ]
