# Generated by Django 2.2.4 on 2020-06-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Narmadiya', '0023_blooddonor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanDakshina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='Full Name')),
                ('address', models.CharField(default='', max_length=30, verbose_name='Address')),
                ('mob', models.BigIntegerField(default=0, verbose_name='Mobile Number')),
            ],
        ),
        migrations.CreateModel(
            name='Sampark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='Full Name')),
                ('address', models.CharField(default='', max_length=30, verbose_name='Address')),
                ('mob', models.BigIntegerField(default=0, verbose_name='Mobile Number')),
            ],
        ),
    ]
