# Generated by Django 2.2.4 on 2020-06-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Narmadiya', '0025_sanstha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanstha',
            name='xcoordinate',
        ),
        migrations.RemoveField(
            model_name='sanstha',
            name='ycoordinate',
        ),
        migrations.AddField(
            model_name='sanstha',
            name='gmap',
            field=models.CharField(default='', max_length=500, verbose_name='Map'),
        ),
    ]
